### ISSUE TITLE
Automatic includes resolution

### ISSUE THREAD

**Issue by fesor** [fesor/fractal-bundle#2]
Add configurable option to automatically resolve includes from request. Something like:

```
fractal:
    includes_auto_parse:
         enabled: true
         query: 'include'
```
